# $ THIS FILE IS MEANT FOR VIEWING EXAMPLE ENTITIES FROM THE API

###
# * YouTube Channels (mine)
# * https://developers.google.com/youtube/v3/docs/channels
# @name channelsRes
GET {{CHANNELS_URL}}?mine=true&part=snippet,contentDetails,statistics,topicDetails,status,brandingSettings,contentOwnerDetails,localizations
Authorization: Bearer {{$dotenv ACCESS_TOKEN}}

###
# * YouTube Playlists (beloging to me)
# * https://developers.google.com/youtube/v3/docs/playlists
# @name playlistsRes

GET {{PLAYLISTS_URL}}?mine=true&part=snippet,status,contentDetails,player,localizations
Authorization: Bearer {{$dotenv ACCESS_TOKEN}}

###
# * YouTube Playlist Items (belonging to playlist)
# * https://developers.google.com/youtube/v3/docs/playlistItems
# @name playlistItemsRes

GET {{PLAYLIST_ITEMS_URL}}?playlistId={{playlistsRes.response.body.items[0].id}}&part=snippet,contentDetails,status
Authorization: Bearer {{$dotenv ACCESS_TOKEN}}